// <auto-generated />
using System;
using LifeBridgesJobApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeBridgesJobApplication.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221027095839_createtable")]
    partial class createtable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LifeBridgesJobApplication.Models.Application", b =>
                {
                    b.Property<int>("autoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("autoid"), 1L, 1);

                    b.Property<string>("AppDisposition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("authorizedinus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("canprovidedoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cellcarrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cellphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificatelist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificateorlicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("collegedegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("convictedofcrime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateapplied")
                        .HasColumnType("datetime2");

                    b.Property<string>("driverslicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencyaddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencycontact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencyrelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencytelephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faultaccidents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstchoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("highschooldiploma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeaddressCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeaddressState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeaddressStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeaddressZip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("howfindout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleinitial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("positionother")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("priorconvictions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondchoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sexoffender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trafficviolations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("autoid");

                    b.ToTable("Application", (string)null);
                });

            modelBuilder.Entity("LifeBridgesJobApplication.Models.EmpReference", b =>
                {
                    b.Property<int>("autoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("autoid"), 1L, 1);

                    b.Property<int>("appid")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employersphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentdatefrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentdateto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reasonforleaving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supervisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("autoid");

                    b.ToTable("EmpReference", (string)null);
                });

            modelBuilder.Entity("LifeBridgesJobApplication.Models.PerReference", b =>
                {
                    b.Property<int>("autoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("autoid"), 1L, 1);

                    b.Property<int>("appid")
                        .HasColumnType("int");

                    b.Property<string>("appposition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goodfit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goodfitwhy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("knowapp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strengths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teamoralone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teamoralonewhy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weakness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yearsknown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("autoid");

                    b.ToTable("PerReference", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
